version: '3'

services:
  node-api:
    build: .
    command: npm start
    depends_on:
      - 'mysql'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/app
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: midway_challenge
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: America/Sao_Paulo
    ports:
      - '3306:3306'
    volumes:
      - './scripts:/docker-entrypoint-initdb.d'
    expose:
      - '3306'
