const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = ['./index.js'];

const doc = {
  info: {
    version: '1.0.0',
    title: 'Midway Challenge',
    description:
      'Documentation automatically generated by the <b>swagger-autogen</b> module.',
  },
  host: 'localhost:3000',
  basePath: '/',
  schemes: ['http'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      name: 'Products',
      description: 'Endpoints',
    },
    {
      name: 'Purchase',
      description: 'Endpoints',
    },
  ],
  definitions: {
    ProductResponse: {
      $name: 'Calça',
      $value: 100.0,
      $inventory: 10,
      $size: 'GG',
      $type: 'Jeans',
      $description: 'Calça jeans masculina',
      dateOfRegistration: '2021-08-31 17:05:19',
      dateOfUpdate: '2021-09-03 17:05:19',
    },
    ProductBody: {
      $name: 'Calça',
      $value: 100.0,
      $inventory: 10,
      $size: 'GG',
      $type: 'Jeans',
      $description: 'Calça jeans masculina',
    },
    ProductToUpdate: {
      name: 'Calça',
      value: 50.0,
      inventory: 10,
      size: 'GG',
      type: 'Jeans',
      description: 'Calça jeans masculina',
    },
    ProductSanitized: {
      productsBeforeSanitize: [{}],
      productsAfterSanitize: [{}],
    },
    Purchase: {
      $productId: 3,
      $customerCPF: '487.459.470-07',
      id: 1,
      invoiceId: 'acfc317e-d69a-423b-99df-2163b80cabfe',
      dateOfPurchase: '2021-09-03 17:05:19',
      isActive: true,
    },
  },
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require('./index.js');
});
